### ISSUE TITLE
Don´t work as expected with ffmpeg

### ISSUE THREAD

**Issue by Classsic** [flaviostutz/rtsp-relay#2]
Hi, I try to use FFMPEG input, but the proxy consume continuously, not only when a client connect to the proxy url.
Normally the rtsp-proxy, consume the origin when get one o more request for clients.
You think is possible to fix the code to work like a real rtsp-proxy?
BTW, this projects is useful.
Thanks

**Comment by flaviostutz** [comment]
In your case it is a problem if there is a single client connected even if no consumer is connected do the proxy? Would you explain more your case pls?

**Comment by Classsic** [comment]
Yes, this is my docker-compose.yml
`version: '3.7'

services:

  rtsp-relay:
    build: .
    image: flaviostutz/rtsp-relay
    ports: 
      - 8554:8554
      - 8000:8000
      - 8001:8001
    environment:
      # - SOURCE_URL=http://93.87.72.254:8090/mjpg/video.mjpg
      # - SOURCE_URL=http://wmccpinetop.axiscam.net/mjpg/video.mjpg
      - SOURCE_URL=rtsp://localhost/101
      - RTSP_PROXY_SOURCE_TCP=yes #<-----This is deprecated apparently, now use  'protocol: tcp' 
      - FFMPEG_ARGS="-rtsp_transport tcp"
      - FORCE_FFMPEG_SOURCE=true
      - FFMPEG_INPUT_ARGS=-rtsp_transport tcp
     # - FFMPEG_OUTPUT_ARGS="-rtsp_transport tcp"`
This launch a ffmpeg process, inclusive if there is no client connect to the proxy.
Please letme know if I´m doing something wrong.

**Comment by flaviostutz** [comment]
I think this is a desired enhancement. If I got it right, it doesn’t seem like a bug, right?

I am not working on new enhancements for RTSP-proxy for now because of other priorities, but if you would like to contribute with this enhancement I would be glad to help.

Thanks!

Flávio Stutz
