### ISSUE TITLE
About mjpeg rtsp stream

### ISSUE THREAD

**Issue by opo2000tw** [flaviostutz/rtsp-relay#5]
# Error or warnning
- Fixed: https://stackoverflow.com/questions/53207692/libav-mjpeg-encoding-and-huffman-table
   
```
Add -huffman 0
```

- Fixed: https://lists.ffmpeg.org/pipermail/libav-user/2015-December/008715.html
```
Add -force_duplicated_matrix 1 
it maybe just warning
```

- Fixed: https://stackoverflow.com/questions/30782771/what-does-past-duration-x-xxx-too-large-mean
```
Add -force_duplicated_matrix 1 
timestamp over than 0.6s or somtimes start first time, it maybe just warning
```

That's all about mjpeg issue

**Comment by flaviostutz** [comment]
Sorry but I didn't get what is this issue about. Are having this issue while using the relay? Would you like to have this fix on this project?
