### ISSUE TITLE
Kubernetes variant

### ISSUE THREAD

**Issue by cedricve** [flaviostutz/rtsp-relay#6]
Hello @flaviostutz 

Thank you so much for your work, just to let you know we made the Kubernetes implementation of your work and hosted it here: https://github.com/kerberos-io/virtual-rtsp.

Thanks for the great work done!
Cedric

**Comment by flaviostutz** [comment]
Hi, @cedricve! Great work there as well! I am honored by your care in getting this back to me. Thanks!
