### ISSUE TITLE
RTP support

### ISSUE THREAD

**Issue by mduzgun** [flaviostutz/rtsp-relay#7]
hi.
Is there possible create rtp streaming instead of rtsp?
Can I use "rtp://localhost:8000/stream"  ? 
I tried this url but VLC does not play it, I received error.
How do I configure parameter for rtp?
Thanks

**Comment by flaviostutz** [comment]
Hi! Currently it supports only the RTSP protocol. Maybe you can try to take a look at the source code and see if you can change the ffmpeg call. If you manage to do it, please let's discuss a PR :)
